### PR TITLE
Fix EvReflection warnings `WARNING: The class 'ServerRoute' is not key value coding-compliant for the key '`

### LINKED ISSUE #76: WARNING: The class 'ServerRoute' is not key value coding-compliant for the key 'arch'
Run-time warning:

```
WARNING: The class 'ServerRoute' is not key value coding-compliant for the key 'arch'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information
```

### PR DESCRIPTION
**Pull request by codedentwickler**
fix: Override setValue in EVReflection Model classes to ignore undefined keys in the JSON response that couldn't be mapped to swift types. fixes #76

### CODE REVIEW

File: AmahiAnywhere/AmahiAnywhere/Data/Remote/Model/Server.swift [hunk 1]
```diff
@@ -16,4 +16,10 @@ public class Server: EVNetworkingObject {
     public var name: String? =              nil
     public var session_token: String? =     nil
     public var active: Bool =               false
+    
+    override public func setValue(_ value: Any!, forUndefinedKey key: String) {
+        if key == "active" {
```
Comment (csoni111) [inline AmahiAnywhere/AmahiAnywhere/Data/Remote/Model/Server.swift]: This is not required here. It automatically parses and sets the value for `active` key.

Comment (codedentwickler) [reply AmahiAnywhere/AmahiAnywhere/Data/Remote/Model/Server.swift]: At work, I have had cases where EVReflection doesn't set Bool values for some reason. In such cases, the default `false` value will be set. I have experienced this many times. It might be difficult to figure out this out later if it becomes an issue. Ensuring the value is set by overriding setValue is just a precaution that I have adopted and it has no drawback.
